import React, { useEffect } from 'react';
import styled from 'styled-components';
import { media } from '@design/media';

const StyledLoaderContainer = styled.div`
    width: 100vw;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
`;
const StyledLoader = styled.div`
    .cls-1 {
        fill: #fff;
    }
    .cls-2 {
        fill: #9d1d59;
    }
    .cls-3 {
        fill: none;
        stroke: #fff;
        stroke-miterlimit: 10;
        stroke-width: 2px;
    }

    /***************************************************
 * Generated by SVG Artista on 10/10/2020, 3:10:18 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

    /***************************************************
 * Generated by SVG Artista on 10/10/2020, 4:23:54 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/
    svg {
        width: 40vw;
        height: 100vh;
        ${media.bigDesktop`
        width: 40vw;
    `};
        ${media.desktop`
        width: 50vw;
    `};
        ${media.thone`
        width: 90vw;
    `};
    }

    svg .svg-elem-1 {
        stroke-dashoffset: 333.3440856933594px;
        stroke-dasharray: 333.3440856933594px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
    }

    svg.active .svg-elem-1 {
        stroke-dashoffset: 0;
        fill: rgb(255, 255, 255);
    }

    svg .svg-elem-2 {
        stroke-dashoffset: 272.57586669921875px;
        stroke-dasharray: 272.57586669921875px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
    }

    svg.active .svg-elem-2 {
        stroke-dashoffset: 0;
        fill: rgb(255, 255, 255);
    }

    svg .svg-elem-3 {
        stroke-dashoffset: 443.8226318359375px;
        stroke-dasharray: 443.8226318359375px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
    }

    svg.active .svg-elem-3 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-4 {
        stroke-dashoffset: 297.2400207519531px;
        stroke-dasharray: 297.2400207519531px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
    }

    svg.active .svg-elem-4 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-5 {
        stroke-dashoffset: 271.5008239746094px;
        stroke-dasharray: 271.5008239746094px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s;
    }

    svg.active .svg-elem-5 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-6 {
        stroke-dashoffset: 416.0603942871094px;
        stroke-dasharray: 416.0603942871094px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s;
    }

    svg.active .svg-elem-6 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-7 {
        stroke-dashoffset: 272.57586669921875px;
        stroke-dasharray: 272.57586669921875px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s;
    }

    svg.active .svg-elem-7 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-8 {
        stroke-dashoffset: 132.33302307128906px;
        stroke-dasharray: 132.33302307128906px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s;
    }

    svg.active .svg-elem-8 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-9 {
        stroke-dashoffset: 157.48016357421875px;
        stroke-dasharray: 157.48016357421875px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.96s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s;
    }

    svg.active .svg-elem-9 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-10 {
        stroke-dashoffset: 152.70204162597656px;
        stroke-dasharray: 152.70204162597656px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s;
    }

    svg.active .svg-elem-10 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-11 {
        stroke-dashoffset: 70.08004760742188px;
        stroke-dasharray: 70.08004760742188px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s;
    }

    svg.active .svg-elem-11 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-12 {
        stroke-dashoffset: 168.1636962890625px;
        stroke-dasharray: 168.1636962890625px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3199999999999998s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s;
    }

    svg.active .svg-elem-12 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-13 {
        stroke-dashoffset: 170.23582458496094px;
        stroke-dasharray: 170.23582458496094px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.44s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s;
    }

    svg.active .svg-elem-13 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-14 {
        stroke-dashoffset: 132.3330535888672px;
        stroke-dasharray: 132.3330535888672px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.56s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s;
    }

    svg.active .svg-elem-14 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-15 {
        stroke-dashoffset: 94.31997680664062px;
        stroke-dasharray: 94.31997680664062px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.68s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.2s;
    }

    svg.active .svg-elem-15 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-16 {
        stroke-dashoffset: 139.0745849609375px;
        stroke-dasharray: 139.0745849609375px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7999999999999998s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.3s;
    }

    svg.active .svg-elem-16 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-17 {
        stroke-dashoffset: 158.13829040527344px;
        stroke-dasharray: 158.13829040527344px;
        fill: transparent;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.92s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.4000000000000004s;
    }

    svg.active .svg-elem-17 {
        stroke-dashoffset: 0;
        fill: rgb(157, 29, 89);
    }

    svg .svg-elem-18 {
        stroke-dashoffset: 99px;
        stroke-dasharray: 99px;
        transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 2.04s, fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.5s;
    }

    svg.active .svg-elem-18 {
        stroke-dashoffset: 0;
    }
`;

const Loader = props => {
    useEffect(() => {
        const start = setTimeout(() => {
            document.getElementById('logo').classList.add('active');
        }, 10);
        const erase = setTimeout(() => {
            document.getElementById('logo').classList.remove('active');
        }, 3000);
        const end = setTimeout(() => {
            if (props.onFinishLoad) {
                props.onFinishLoad();
            }
        }, 6010);
        return () => {
            clearTimeout(start);
            clearTimeout(erase);
            clearTimeout(end);
        };
    }, [props]);

    return (
        <StyledLoaderContainer>
            <StyledLoader>
                <svg id="logo" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 598.72 97">
                    <title>logo</title>
                    <path d="M53.14,32c-13.06-17.73-40.39-6.89-40,14.38C12.35,66.78,39.76,79,52.48,61.5H67.15C51.9,95.78.13,83.09.5,46.18.43,9.16,52.68-2.11,67.52,32Z" transform="translate(0)" fill="#fff" stroke="#fff" strokeMiterlimit="10" className="svg-elem-1"></path>
                    <path d="M124.3,11.31v70.5H110.85V68.08c-9.11-13.44-29.51-43.19-38.91-56.77H87.07c5.35,7.54,18.75,26.64,23.78,34v-34Z" transform="translate(0)" fill="#fff" stroke="#fff" strokeMiterlimit="10" className="svg-elem-2"></path>
                    <path d="M185.58,11.31v70.5H171.11L141.69,30.58h-.29V81.81H128.34V11.31h14.94l29.14,51.32h.29V23.43H160.58V11.31Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-3"></path>
                    <path d="M190.47,11.21h38V23.53H203.54v17.2h14.1V53h-14.1V69.59h24.91V81.81h-38Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-4"></path>
                    <path d="M280.52,81.81H264.73L239.35,45.05c3.63,0,11.28,0,15,0,16.52,1,16.41-22.4,0-21.52-5,0-16.35,0-21.43,0V11.4c10.94.84,29.56-2.8,38.72,4.7,14.87,11,8.32,37.37-10.15,39.76Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-5"></path>
                    <path d="M357.79,45.8l-23,33.66C307,91,275.38,60.59,288.7,32.69c11.06-27.75,55.19-28.31,66-.14H339.74c-9.4-15-33.78-11.31-39.67,4.89-7.42,16.91,8.62,36.33,26.7,32.24l8.46-12H314V45.8Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-6"></path>
                    <path d="M403.57,11.31v70.5H390.12V68.08C381,54.64,360.61,24.89,351.21,11.31h15.13c5.35,7.54,18.75,26.64,23.78,34v-34Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-7"></path>
                    <path d="M465,36.26c-8.27,10.62-27.08,3.87-26.44-9.72-.66-13.08,17.3-20.28,25.72-10.28l-3.8,3.68c-5.35-6.8-17.12-2-16.52,6.6-.58,9.14,12,13.44,17.2,6.08Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-8"></path>
                    <path d="M482.43,41.5C463,42,463,11.05,482.43,11.58,501.9,11.05,501.9,42,482.43,41.5Zm0-5.12c12.53.37,12.53-20,0-19.68C469.9,16.34,469.9,36.75,482.43,36.38Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-9"></path>
                    <path d="M501.75,12.22c10.87-.79,24.64.16,24.4,14.33.28,14.18-13.55,15.1-24.4,14.31Zm9.44,23.52c14.41-.22,12.7-21.34-4-18.4v18.4Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-10"></path>
                    <path d="M530.51,12.22h5.4V40.86h-5.4Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-11"></path>
                    <path d="M541.67,12.22H548l11.52,19.2h.32c-.4-3.62-.33-15.37-.32-19.2h5.36V40.86h-5.68L547,20.58h-.32c.42,3.66.32,16.41.32,20.28h-5.32Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-12"></path>
                    <path d="M583.79,25.14h14c3.86,16.93-21.94,22.57-27.84,7.38-7-14.89,14-28.38,24.84-16.42l-3.72,3.64c-7.24-8.06-20.74,1-16.14,10.87,2.91,7.79,16.29,7.8,17.82-.87h-9Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-13"></path>
                    <path d="M465,76.26c-8.27,10.62-27.08,3.87-26.44-9.72-.66-13.08,17.3-20.28,25.72-10.28l-3.8,3.68c-5.35-6.8-17.12-2-16.52,6.6-.58,9.14,12,13.44,17.2,6.08Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-14"></path>
                    <path d="M469.27,52.22h5.4V75.74h12.12v5.12H469.27Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-15"></path>
                    <path d="M500.71,81.5c-14.94.62-10.51-20.08-11.12-29.28H495c1.11,5.33-3.7,24.5,5.72,24.16,9.47.42,4.66-18.87,5.76-24.16h5.4C511.3,61.47,515.62,82,500.71,81.5Z" transform="translate(0)" fill="#9d1d59" stroke="#9d1d59" strokeMiterlimit="10" className="svg-elem-16"></path>
                    <path
                        d="M517,52.22c2.63.19,12.32-.49,14.64.58,6,1.65,7.35,10.48,1.48,13.06v.32c7,2.14,6,12.47-.86,14.12-2.43,1-12.55.39-15.26.56Zm10.8,11.68a3.47,3.47,0,0,0,2.92-5.84c-1.34-1.66-6.44-.79-8.32-1V63.9Zm.6,12a3.7,3.7,0,0,0,3.1-6.3c-1.47-1.72-7-.86-9.1-1.06V75.9Z"
                        transform="translate(0)"
                        fill="#9d1d59"
                        stroke="#9d1d59"
                        strokeMiterlimit="10"
                        className="svg-elem-17"
                    ></path>
                    <line x1="421.74" x2="421.74" y2="97" fill="none" stroke="#fff" strokeMiterlimit="10" strokeWidth="3" className="svg-elem-18"></line>
                </svg>
            </StyledLoader>
        </StyledLoaderContainer>
    );
};
export default Loader;
